# Generated by Django 5.1.15 on 2026-09-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('success', 'Başarılı'), ('failed', 'Hatalı'), ('running', 'Çalışıyor')], db_index=True, default='success', max_length=20)),
                ('items_count', models.IntegerField(default=0)),
                ('log_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Senkronizasyon Günlüğü',
                'verbose_name_plural': 'Senkronizasyon Günlükleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
